"""Adiciona campo is_verified a Prestador"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d877e98ef47'
down_revision = '69fad0c74de0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
